### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Deyclan** [PolytechLyon/isi3-test-serrano-piard-tp7#1]
Bonjour @Slashgear,

Pourriez vous jeter un oeil sur notre code + rapport pour ce tp ? 
Faut-il que l'on détaille plus le rapport ? 

Merci d'avance ! 

Bien cordialement, 
Brandon Piard.

**Comment by Slashgear** [comment]
ça me suffit. Mais attention l'approche TDD ne signifie pas qu'il faut que **Tout** le projet soit bien spécifié. Uniquement la brique qu'on te demande de rajouter.

Et cela permet de rapidement mettre en lumière des "trous" dans les spécifications.
